name: "Build Form"
on:
  workflow_dispatch:
    inputs:
      shield:
        description: "Select the shield (Keyboard)"
        required: true
        type: choice
        options:
          - Corne
          - Lily58
      board:
        description: "Enter the board (Microcontroller)"
        required: true
        default: "nice_nano_v2"
        type: string
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      board: ${{ github.event.inputs.board }}
      shield: ${{ github.event.inputs.shield }}
